apiVersion: apps/v1
kind: Deployment
metadata:
  name: mymicrobot
  labels:
    app: mymicrobot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mymicrobot
  template:
    metadata:
      labels:
        app: mymicrobot
    spec:
      containers:
      - name: mymicrobot
        image: "dontrebootme/microbot:v1"
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: mymicrobot
  labels:
    app: mymicrobot
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: mymicrobot
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mymicrobot
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - mymicrobot.local
    secretName: mymicrobot-tls
  rules:
  - host: mymicrobot.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: mymicrobot
            port:
              number: 80