replicaCount: 1

image:
  repository: dontrebootme/microbot
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false
  hostname: ""
  tls:
    enabled: false
    issuerName: ""