{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "MyMicroBotDemo.fullname" . }}
  labels:
    {{- include "MyMicroBotDemo.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.issuerName }}
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ include "MyMicroBotDemo.fullname" . }}
            port:
              number: 80
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    secretName: {{ include "MyMicroBotDemo.fullname" . }}-tls
  {{- end }}
{{- end }}

